# Generated by Django 5.0.6 on 2024-06-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='bars/images/')),
                ('url', models.URLField(blank=True)),
                ('star', models.CharField(max_length=2)),
            ],
        ),
    ]
